blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogListView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("", BlogListView.as_view(), name="blog_list"),
    path("view/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("edit/<int:pk>/", BlogUpdateView.as_view(), name="blog_edit"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mails.urls", namespace="mails")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

congig/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from congig import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mails.urls", namespace="mails")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import User


NULLABLE = {"blank": True, "null": True}


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    slug = models.CharField(max_length=200, verbose_name="slug", **NULLABLE)
    content = models.TextField(verbose_name="Содержание")
    image = models.ImageField(
        upload_to="blog/image", **NULLABLE, verbose_name="Изображение"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=True, verbose_name="Опубликовано")
    view_counter = models.PositiveIntegerField(
        default=0, verbose_name="Счетчик просмотров", editable=False
    )
    owner = models.ForeignKey(
        User,
        verbose_name="Автор",
        help_text="Укажите автора статьи",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

blog/views.py
from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    CreateView,
    ListView,
    UpdateView,
    DeleteView,
    DetailView,
)
from pytils.translit import slugify
from blog.models import Blog


class BlogCreateView(CreateView, LoginRequiredMixin):
    model = Blog
    fields = ("title", "slug", "content", "image", "is_published")
    template_name = "blog/blog_form.html"
    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        blog = form.save()
        user = self.request.user
        blog.owner = user
        blog.save()
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog
    template_name = "blog/blog_list.html"

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog
    template_name = "blog/blog_detail.html"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_counter += 1
        self.object.save(
            update_fields=["view_counter"]
        )  # Only update view_counter field
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ("title", "slug", "content", "image", "is_published")
    template_name = "blog/blog_form.html"

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("blog:blog_detail", args=[self.kwargs.get("pk")])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")

blog/templates/blog/blog_confirm_delete.html
{% extends 'mails/home.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                        </div>
                        <p class="card-text">Удалить эту статью? {{ object.title }}</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Отменить</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mails/home.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="col">
            <div class="card shadow-sm">
                <div class="card-header">
                    <h4 class="card-title">"{{ object.title }}" ({{ object.slug }})</h4>
                </div>
                <img src="{{ object.image | media_filter }}">
                <div class="card-body">
                    <p class="card-text">
                        {{ object.content }} Создано:{{ object.created_at}}
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="d-grid gap-2 d-md-block">
                            <div class="btn-group">
                                <p>
                                    <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Назад</a>

                                {% if perms.blog.change_blog and perms.blog.delete_blog or user == object.owner %}
                                    <a class="btn btn-warning" href="{% url 'blog:blog_edit' object.pk %}"
                                       role="button">Редактировать</a>
                                    <a class="btn btn-danger" href="{% url 'blog:blog_delete' object.pk %}"
                                       role="button">Удалить</a>

                                </p>
                                {% endif %}
                            </div>
                            <div class="card-footer">
                                Просмотры: {{ object.view_counter}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mails/home.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mails/home.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="col-12 mb-5">
            {% if user.is_authenticated %}
            <p>
                <a class="btn btn-primary" href="{% url 'blog:blog_create' %}">Добавить статью</a>
            </p>
            {% endif %}
        </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ object.image | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">
                            {% if object.is_published %}
                            {{ object.title }}

                            {% else %}
                            <span class="badge bg-secondary text-white">
                                {{ object.title }}

                            </span>
                            {% endif %}
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <p>
                                    <a class="btn btn-primary" href="{% url 'blog:blog_detail' object.pk %}"
                                       role="button">Перейти</a>

                                {% if perms.blog.change_blog and perms.blog.delete_blog or user == object.owner %}

                                    <!-- Действие, если условия выполняются -->
                                    <a class="btn btn-warning" href="{% url 'blog:blog_edit' object.pk %}"
                                       role="button">Редактировать</a>
                                    <a class="btn btn-danger" href="{% url 'blog:blog_delete' object.pk %}"
                                       role="button">Удалить</a>
                                </p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}