blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogListView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("", BlogListView.as_view(), name="blog_list"),
    path("view/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("edit/<int:pk>/", BlogUpdateView.as_view(), name="blog_edit"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mails.urls", namespace="mails")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

congig/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from congig import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mails.urls", namespace="mails")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mails/urls.py
from django.urls import path
from mails.apps import MailsConfig
from mails.views import (
    RecipientListView,
    RecipientDetailView,
    RecipientCreateView,
    RecipientUpdateView,
    RecipientDeleteView,
    SendingListView,
    SendingDeleteView,
    SendingCreateView,
    SendingDetailView,
    SendingUpdateView,
    MaillListView,
    MaillDetailView,
    MaillCreateView,
    MaillUpdateView,
    MaillDeleteView,
    contact,
    about,
    HomePageView,
    EventReportView,
)

app_name = MailsConfig.name

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("recipient_list", RecipientListView.as_view(), name="recipient_list"),
    path(
        "recipient_view/<int:pk>/", RecipientDetailView.as_view(), name="recipient_view"
    ),
    path("recipient_create/", RecipientCreateView.as_view(), name="recipient_create"),
    path(
        "recipient_update/<int:pk>/",
        RecipientUpdateView.as_view(),
        name="recipient_update",
    ),
    path(
        "recipient_delete<int:pk>/",
        RecipientDeleteView.as_view(),
        name="recipient_delete",
    ),
    path("sending_list/", SendingListView.as_view(), name="sending_list"),
    path("sending_create/", SendingCreateView.as_view(), name="sending_create"),
    path(
        "sending_delete/<int:pk>/", SendingDeleteView.as_view(), name="sending_delete"
    ),
    path(
        "sending_update/<int:pk>/", SendingUpdateView.as_view(), name="sending_update"
    ),
    path(
        "sending_detail/<int:pk>/", SendingDetailView.as_view(), name="sending_detail"
    ),
    path("maill_list/", MaillListView.as_view(), name="maill_list"),
    path("maill_create/", MaillCreateView.as_view(), name="maill_create"),
    path("maill_delete/<int:pk>/", MaillDeleteView.as_view(), name="maill_delete"),
    path("maill_update/<int:pk>/", MaillUpdateView.as_view(), name="maill_update"),
    path("maill_detail/<int:pk>/", MaillDetailView.as_view(), name="maill_detail"),
    path("event-report/", EventReportView.as_view(), name="event_report"),
    path("contact/", contact, name="contact"),
    path("about/", about, name="about"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (
    UserCreateView,
    email_verification,
    UserProfileView,
    reset_password,
    UserListView,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("profile/<int:pk>/", UserProfileView.as_view(), name="profile"),
    path("reset-password/", reset_password, name="reset_password"),
    path("email-confirm/<str:token>/", email_verification, name="email_confirm"),
    path("user_list/", UserListView.as_view(), name="user_list"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="Email")
    company = models.CharField(max_length=100, verbose_name="Название компании")
    avatar = models.ImageField(
        upload_to="users/", blank=True, null=True, verbose_name="Аватар"
    )
    phone = models.CharField(
        max_length=35, blank=True, null=True, verbose_name="Телефон"
    )
    country = models.CharField(
        max_length=35, blank=True, null=True, verbose_name="Страна"
    )
    is_active = models.BooleanField(default=False, verbose_name="Активный")
    token = models.CharField(
        max_length=255, verbose_name="Токен", blank=True, null=True
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.email}"

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        ordering = ["company"]
        permissions = [
            ("can_block_users", "Can block users"),
            ("can_view_users", "Can view users"),
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("email", "company", "avatar", "phone", "country")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password"].widget = forms.HiddenInput()


class UserProfileManagerForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("is_active", "email")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password"].widget = forms.HiddenInput()

users/views.py
import random
import secrets
import string
from django.contrib.auth.hashers import make_password
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserProfileForm, UserProfileManagerForm
from users.models import User


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save(update_fields=["token", "is_active"])
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}"

        send_mail(
            subject="Подтверждение регистрации",
            message=f"Перейдите по ссылке для подтверждения регистрации {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


def generate_random_password(length=10):
    # Генерация случайного пароля из букв и цифр
    characters = string.ascii_letters + string.digits

    return "".join(random.choice(characters) for _ in range(length))


def reset_password(request):
    if request.method == "POST":
        email = request.POST.get("email")
        user = User.objects.filter(email=email).first()

        if user:
            new_password = generate_random_password()
            user.password = make_password(new_password)
            user.save()

            # Отправка письма с новым паролем
            send_mail(
                "Восстановление пароля",
                f"Ваш новый пароль: {new_password}",
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email],
                fail_silently=False,
            )
            success_message = "Пароль сброшен на ваш email."
        else:
            success_message = "Пользователь с таким email не найден."

        return render(
            request, "users/reset_password.html", {"success_massage": success_message}
        )

    # Если метод не POST, рендерим страницу сброса пароля (GET запрос)
    return render(request, "users/reset_password.html")


class UserProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy("mails:home")

    def get_object(self, queryset=None):
        pk = self.kwargs.get("pk")
        if pk:
            return get_object_or_404(User, pk=pk)
        raise Http404("User not found")

    def get_form_class(self):
        user = self.request.user
        if user == self.get_object():
            return UserProfileForm
        if user.has_perm("users.can_block_users"):
            return UserProfileManagerForm
        raise PermissionDenied


class UserListView(ListView):
    model = User
    template_name = "users/user_list.html"

    def get_queryset(self, *args, **kwargs):
        # Исключаем суперпользователя с email 'admin@example.com'
        queryset = User.objects.exclude(email="admin@example.com")
        return queryset

users/templates/users/register.html
{% extends 'mails/home.html' %}
{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Регистрация</h5>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Зарегистрироваться
                </button>
            </div>
            <div class="card-footer">
                <div class="d-grid col-12">
                    <div class="btn-group">
                        <a href="{% url 'users:login' %}" class="btn btn-outline-info">Вход</a>
                        <a href="{% url 'users:reset_password' %}" class="btn btn-outline-info">Восстановить пароль</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/reset_password.html
{% extends 'mails/home.html' %}
{% block content %}

<div class="col-12">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Восстановление пароля</h5>
            </div>
            <div class="card-body">
                {% if success_massage %}
                    <p>{{ success_massage }}</p>
                    <a href="{% url 'mails:home' %}" class="btn btn-outline-secondary">На главную</a>
                {% else %}
                    <form class="row" method="post">
                        {% csrf_token %}
                        <p>Введите email:
                            <input type="email" name="email" required>
                        </p>
                        <button type="submit" class="btn btn-primary">Восстановить пароль</button>
                    </form>
                {% endif %}
            </div>
        </div>
        <div class="card-footer">
            <div class="d-grid col-12">
                <div class="btn-group">
                    <a href="{% url 'users:register' %}" class="btn btn-outline-info">Регистрация</a>
                    <a href="{% url 'users:login' %}" class="btn btn-outline-info">Вход</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mails/home.html' %}
{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Профиль</h5>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Сохранить
                </button>
            </div>
            <div class="card-footer">
                <div class="d-grid col-12">
                    <a href="{% url 'mails:home' %}" class="btn btn-outline-secondary">Назад</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mails/home.html' %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">
                            {{ object.email }}
                            {{ object.is_active }}
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <p>
                                    {% if object.pk %}
                                    <a class="btn btn-outline-warning" href="{% url 'users:profile' object.pk %}"
                                       role="button">Редактировать</a>
                                    {% else %}
                                    <span class="btn btn-outline-warning disabled">Редактировать</span>
                                    {% endif %}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}